### ISSUE TITLE
move types of initiatives, that do not have 2nd level to 3rd level

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#1]
@keikreutler 

I want to emphasize again, how happy I am about the current development, [as stated in Taiga](https://tree.taiga.io/project/transformap/us/31) : )

The menu structure looks really good, it has some small glitches, but looks very good, even on my smartphone.

---

**Issue:**
As described here in the [Taiga task #305](https://tree.taiga.io/project/transformap/task/305)
- Those types of initiatives, that do not have a 2nd level category (sub-category) are mis-represented in the 2nd level of the structure (that one, that downfolds)
- They should open to the right (orange), once the category without sub-category is selected.

**Comment by species** [comment]
fixed by reimplementation of filter menu in a41e8eb0e6794c77f464d1e34c48d786d1d32661.
