### ISSUE TITLE
transparency in name-preview window make names sometimes unreadable

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#10]
The set transparency in the "name-preview window" (for lack of better words), makes it often unreadable, espeicially if the POI is in a crowded area with many POIs. 

Full white would be the easiest, I guess, and does the job.

**Comment by species** [comment]
set to 80% white instead of 50% - better now?

**Comment by josef-legacy-account** [comment]
Let´s mark that as done. It is not crucial anymore, and if we get user-feedback, we can open a new one.
