### ISSUE TITLE
mobile version - longer popups (image + text) do not scroll

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#14]
The longer popups do not scroll. It shows either the image, and you can´t scroll down to the text, or shows the text and the lower 30% of the image.

**Comment by species** [comment]
fixed with 34ff4e391c177a4bcebc01de1a4715e05bcd2457. Also changed the way the menu is displayed on small screens.

**Comment by josef-legacy-account** [comment]
nice & sweet!
