### ISSUE TITLE
zoom levels on touchpad and mouse-scroll too fast (Macbook touchpad - not useable)

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#16]
The zoom levels are especially with touchpad too fast, and it is almost impossible to reorient in the opening zoom levels. 

I tested the map viewer interface with a colleague this weekend, and he could not make use of his macbook touchpad, as he would usually navigate a map. The touchpad was so sensitive to the zoom levels, that he was basically shot between scale 0 and scale 18.

I also notice, when I use the scroll-wheel of my mouse to navigate, that it jumps in steps to high for me to visually follow along. It jumps in steps of 4 from zoom level 0 to 4 to 8, ,12, 16. 

---

Solution: 
Is it possible to set scroll/touchpad sensitivity back from 4 to 1 zoom-level per interaction?

**Comment by species** [comment]
Please could you specify on which:1. browser, 2. Operating Systems, 3. mouses this issue exist? It does work normal on FF and the bundled Browser on Android.

I've noticed the zoomwheel issue at Leaflet when working on a Mac with a Magic Mouse at a customer recently. But I don't have any Apple devices here for testing.

**Comment by species** [comment]
Found the issue here:
https://github.com/Leaflet/Leaflet/issues/4410

Meanwhile, you can use th [+] / [-] Buttons in the upper right corner for zooming.

**Comment by species** [comment]
tried to fix in 4cde449402e74c57110a82519a7bf7984146d94c, please test

**Comment by species** [comment]
got positive feedback, closing ticket.
