### ISSUE TITLE
mobile version - show map button more prominent

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#17]
The "show map" button in the mobile version now visually somewhat disappears, as there is 3 more buttons around it. 

---

Could it be possible to make it 
- bright, 
- or more round, 
- or give it some kind of glow, 
  so that it is more visible to be the key next step of the menu. 

Whatever of these options or combination you see best fit and easy to implement.

**Comment by species** [comment]
I've put it on top right, so it is visible initially. Any suggestions to improve it?

**Comment by josef-legacy-account** [comment]
Very good for the moment IMHO. 
Does the job!

I find it very helpful, that a double click on the items also leads to the map. I mostly use it that way.
