### ISSUE TITLE
Tiles choice

### ISSUE THREAD

**Issue by AdrienLab** [TransforMap/transformap-viewer#18]
currently by default the viewer is displaying Stamen Terrain Background. It does a poor job at displaying street (one needs to zoom a lot). 
I would suggest to switch to Stamen Terrain instead. Don't expect the lay user to switch tiles.

**Comment by almereyda** [comment]
I had chosen Terrain Background for showing [no national borders](https://twitter.com/almereyda/status/766650815708889088). Yet this is not totally the case. Unfortunately the Terrain typography is somewhat bold.

Should we play with Terrain Background and overlay some streets and names like Toner lines and names?

**Comment by species** [comment]
@almereyda do you know an overlay style which is a transparent tile layer that only displays road/place names?

**Comment by AdrienLab** [comment]
Yes that's what I thought. I like the idea to see no country borders. 
Can you mix different tiles? which one? what can you do? Because then one could play with mapstack and then once a result is good use the configuration...

**Comment by AdrienLab** [comment]
what about something in this direction http://mapstack.stamen.com/edit.html#watercolor[alpha=60];positron[comp=multiply]/9/52.5288/13.4500

**Comment by almereyda** [comment]
I think from the moment on we want to see lines, there is going to be
borders:

1.
http://mapstack.stamen.com/edit.html#terrain-background;toner-hybrid[tint=$88cc00@100,comp=multiply,alpha=60]/9/52.5288/13.4500
2.
http://mapstack.stamen.com/edit.html#terrain-background;toner-labels[tint=$88cc00@100,comp=multiply,alpha=60]/9/52.5288/13.4500

We would have to render our own background tiles or build upon WebGL maps,
if we want to control this appearance granulary.

**Comment by josef-legacy-account** [comment]
Today at the SUSY-Webinar, we noticed, that Stamen Background Terrain does not have street level zoom, as already noticed by @AdrienLab in the initial post to this thread.

---

We could:
1. set another default view (Stamen Terrain or Humanitarian e.g.)
2. develop some kind of switch, that changes the map tiles at a certain zoom level

Given current priorities, I would prefer option 1.

**Comment by species** [comment]
To suppress any "edit wars" between different actors preferring different backgrounds, the background is now configurable via a parameter in the embedding code. Everyone embedding the viewer can now choose a different default background, see [README.md#embedding](https://github.com/TransforMap/transformap-viewer/blob/gh-pages/README.md#embedding).

**Comment by josef-legacy-account** [comment]
@species thank you for enabling the independent choice per implementation. 
Can the background for the 2 SUSY-Map implementations be set to Mapnik as default?
