### ISSUE TITLE
introduce predefined icon colours, pictograms and design

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#2]
The colours of the POIs are changing each time I open the window. I don´t really understand that. 
I will request the SSEDAS CI-Team if they can provide general colour coding for the map.

**Comment by species** [comment]
Currently, the POI colors are generated randomly on each load of the site. This is of course only to demonstrate the difference in colors and this will not be the way it is done in production. For sure we need predefined colors or icons for the different categories.

**Comment by josef-legacy-account** [comment]
moving aspects from here https://github.com/TransforMap/transformap.github.io/issues/24:
- the points need to be visualized bigger. They are difficult to click. Especially on the table.

**Comment by species** [comment]
as we have only one color now in the reimplementatin, I consider this fixed.
