### ISSUE TITLE
Implement Susy-Logo and Imprint-Text

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#21]
- Implement the Logo: ![susy_logo_whitetext_small](https://cloud.githubusercontent.com/assets/4363790/18108726/d57a498e-6f0d-11e6-8a06-a3dc7efc7626.png)

Link to Logo from Website: http://www.solidarityeconomy.eu/fileadmin/_processed_/csm_SUSY-Logo-NegClaim_af33a15210.png
-  adding the text-disclaimer: 
  >This website has been produced with the financial assistance of the European Union. The contents of this website are the sole responsibility of the SUSY initiative and can under no circumstances be regarded as reflecting the position of the European Union.

[**Example screenshot of where to place the items linked here**.](https://media.taiga.io/attachments/2/3/e/8/587363b090e340706076053aa80913c0ef15a61e0a7b78ad0c79dca1504c/screenshot-example.png)
- Links for "contact" and "imprint" as in the example screenshot above:

http://at.solidarityeconomy.eu/imprint/
http://at.solidarityeconomy.eu/contact/

**Comment by josefkreitmayer** [comment]
- überschrift karte: sollte bitte inkota einbringen
link zu disclaimer, impressum und kontakt siehe oben was den einbau betrifft, links sind dann jene von der www.solidarityeconomy.at zu verwenden, für kontakt und impressum gibt es jeweils einen.
http://at.solidarityeconomy.eu/imprint/
http://at.solidarityeconomy.eu/contact/

**Comment by josef-legacy-account** [comment]
Suggestion, that we implement a small version of the EU-Logo with the disclaimer-text, that relates to the EU: http://www.solidarityeconomy.eu/fileadmin/_processed_/csm_eu-flag_yellow_cb1a72bd33.jpg

**Comment by josef-legacy-account** [comment]
Current state looks great. Following issues still open:
- Links for contacts and Imprint
- Question: Is contacts and imprint hardcoded, or easily translated via weblate, as well as the text below?
- The map goes blank on the bottom, could it go from top to bottom?

**Comment by species** [comment]
all things fixed.
