### ISSUE TITLE
colours of POI-Cluster on map

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#24]
Currently the POI-Cluster colours do not add much information, but distract, as especially the green of the smallest cluster break the colour-pattern. 

---

Best change to the colour pattern of www.solidarityeconomy.us

**Comment by josef-legacy-account** [comment]
For the colour of the actual POI, we could use the green that currently is at the smallest cluster. 

---

3 people here liked it, let´s try. 
The dark blue is not really applealing, and the turquois would probably interfere with colours in the map tiles.

**Comment by species** [comment]
Tried out bright blue for POIs, not really a good idea
![snapshot1](https://cloud.githubusercontent.com/assets/2196350/18146482/3a44dede-6fd0-11e6-9038-4efa1ced070a.png)

**Comment by species** [comment]
changed to solidarity economy us color scheme, used green for pois on standard leaflet marker icon.
