### ISSUE TITLE
Implement various Logos

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#26]
Das SUSY-Logo ist schon einmal gut. Ich würde eventuell das Logo der EU hinzunehmen. Richtig schick wäre es, wenn die einzelnen Partner*innen auf „ihren“ Karten, die sich also in ihre Webseiten ihr eigenes Logo einbinden könnten. Also in Dtld. INKOTA, in Österreich Südwind etc. Geht das?

**Comment by josef-legacy-account** [comment]
Reprasing the question:

How can we enable the partners, which are embedding the website, to easily change that part of the UI, where the logo, etc is displayed?

---

Actually, that would be a good question, but we need to focus on core and longterm sustainability perspective, meaning:
- We will have a one size fits it all solution, with very little individual specifications possible, as e.g. colours.

**Comment by species** [comment]
In today's meeting we decided to remove the logos, as it will be embedded in the existing website only.

**Comment by josef-legacy-account** [comment]
About the embedding only in the existing website, I am not sure actually. Yesterday we just focused on the solidarityeconomy.eu website, and not on the website of the partners. 

So, the requirement for the implementation in the partner websites will be slightly different.
