### ISSUE TITLE
do we actually need zoom buttons on the mobile version

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#27]
Frage: Braucht man auf Handybildschirm Zoom-Buttons überhaupt, das Bild ist sowieso schon so klein, da würde man am Besten alles Unnötige vermeiden.

Gibt es noch Menschen die auf dem Touchscreen über + und - Buttons zoomen, macht das nicht inzwischen jede_r mit Gesten? Vielleicht kann man mal ein paar Teste_rinnen dazu befragen.

**Comment by species** [comment]
Some (old) mobile phones don't support multitouch for zooming (and on newer phones some older users don't know it)
