### ISSUE TITLE
mobile version -  placement of buttons in map view

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#28]
Jan noticed, that the buttons in the map-view on the mobile phone seem to be placed arbitrary. 

His suggestions is to put the buttons in the very top at the same hight as the "back to the map"

> Unwichtig, aber unserem ästhetischen Empfinden nach schöner möglich ist für den Handybildschirm die Anordnung der Buttons rechts und auch des Filterbuttons links auf der Karte. Die sind weder ganz oben noch richtig zentriert, sondern irgendwo dazwischen. warum nicht jeweils in er unteren oder oberen Ecke? Das wäre, wo wir sie zuerst suchen würden, und wo wir sie als am wenigsten störend empfinden würden. Vermutlich oben, da im Filtermenü das "zurück zur Karte" auch oben steht.

**Comment by species** [comment]
it is the problem with closing "x" from the popup... if they are on top, they hide the "X"...

this would need BIG changes in the leaflet lib, don't know if its worth the time...

**Comment by josef-legacy-account** [comment]
No, it´s not worth the time.
