### ISSUE TITLE
design: click boxes instead of +/- for the enhanced filter menu

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#29]
From the feedback from Jan (Inkota), he and his colleage propose to replace the +/- button in the enhanced overview with round or round edged checkboxes. 

---

Reviewing the current solution myself, I noticed, that the +/- does not really give more information than a checked or unchecked checkbox, but is visually slightly more noisy and conceived of the +, as well as the - element, which are integrated in the one element of the checked or unchecked box, and therefor probably easier to read and use.

---

Sidenote, currently in firefox browser, the +/- box from "self organization and mutuality" does not fit any more and makes the menu slip from there.

**Comment by species** [comment]
For TOIs, this is OK.
For cats & subcats:
- make a grey checkbox if only some subcats/tois are checked
- clicking it should
  - if it is grey, activate all
  - if black, deactivate

**Comment by species** [comment]
note to self: the checkbox's "3'rd" state is "indeterminate": https://css-tricks.com/indeterminate-checkboxes/, this is needed for only partially active cats.

**Comment by species** [comment]
Implemented and live, please test.
It uses the Browser's default checkboxes, no time for better graphics.

**Comment by josef-legacy-account** [comment]
strange enough, I notice, that I liked it better before, but anyway. Let´s just leave it as it is, and I will show it to Jan, who requested the change early next week.

In any case, people, that use the expert-function will understand the relations of the boxes after 2 minutes, and then they got it, and can use it.

**Comment by josef-legacy-account** [comment]
It indeed looked much more awsome before with the +/-.
Maybe at some point some designer gives it a little css styling.
