### ISSUE TITLE
suggestion for filter-menu colours to have just one colour for the different elements

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#30]
Jan and his colleague suggest, that we have just one colour for the different levels of the filter menu.

Worth to consider with someone who is experienced with UI design.

**Comment by josef-legacy-account** [comment]
As that would be confusing with the way, the UI in the mobile web-app is constructed, that possibility will not be further evaluated.

---

For explenation: The UI of the mobile version opens the 3rd level of the Filter-Menu as overlay over the 1st and 2nd level. It would be confusing, if that had the same colour.
