### ISSUE TITLE
website-integration country middlepoint geocodes

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#31]
We want to provide the geo-codes of the partner country capitals to provide them to Supertrumpf als starting point for the individual partner sub-sites with the maps

Here is an overview of the geo-codes of capitals: 
http://www.nobochamp.de/hauptstaedte.html

**Comment by josefkreitmayer** [comment]
Supertrumpf was provided with zoom level and geo-codes for a country-middle point for each SSEDAS partner. The decision to implement the individual sites with each partner now lies with the SSEDAS SC. 

The List is als follows:

![grafik](https://cloud.githubusercontent.com/assets/4363790/20528165/6438e726-b0cb-11e6-8965-a2d38c95e86a.png)

**Comment by josefkreitmayer** [comment]
We can send the information as suggestion for the partner site implementation.

**Comment by josef-legacy-account** [comment]
moved here: https://github.com/susy-partners/transformap-viewer/issues/14
