### ISSUE TITLE
Have static json file with geo-data in repo, as fallback, if server goes down

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#32]
As there is always a chance, that the server with the API goes down for administrative or technical reasons, it might be useful to have a fallback json file with the geo-data, which is updated every quater-year, and where the map interface falls back on, if the request to the API is not answered within a certain time. 

That could save a lot of "oh my god, the map is not showing anymore", if some problems with the server arise.

**Comment by species** [comment]
Fixed with 88b15326e22a79f51101aa5bc7fb165da4303c3a, 0238aec888e04bcff6fa29628840eac8f0c65b1f.
