### ISSUE TITLE
Icons for the main filter categories

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#34]
@paulovieira from https://github.com/paulovieira/rede-convergir-3 was so nice to share the source of their wonderful free icons with us yesterday in the ETL call. 

When we have some time, we could have a look, which would be a good match for the main filter-categories in the SUSY-Map: https://mapicons.mapsmarker.com/

**Comment by josef-legacy-account** [comment]
@species here the source of the icons: https://mapicons.mapsmarker.com/

The icons come directly with the map-marker. They have a size of 32x37 and do not need any further processing for the graphics, than plug and play with the respective categories. All of them are from one design, and would fit to each other perfectly.

I searched for other map icons libraries, that fulfill your requirement of 48x48px or vector, and the results are
- a nightmare to search, and not in one clear style, but from several designers
- to complicated design, that we do not need (multicolour design, ... for them you definitely need 48x48 or vector)
- not for free

**Comment by josef-legacy-account** [comment]
Please, let´s just start with https://mapicons.mapsmarker.com/

all the other options that came up are a nightmare to search, and do not come as a readymade marker.
- http://www.flaticon.com/
- https://www.iconfinder.com/search/?q=Map
- http://www.iconarchive.com/search?q=icon+48x48&page=16
- http://individual.icons-land.com/

**Comment by paulovieira** [comment]
One detail: in Leaflet you'll probably have to adjust the offset values when creating L.Icon instances, otherwise the tip of the icon (in the bottom) won't be in the correct place. 

To make sure it is in the correct spot: draw both the icon and a small circle marker in the same point. The tip should be exactly in the center of the circle.

As for other map icons collections, there's also a good one from mapbox: https://www.mapbox.com/maki-icons/

**Comment by species** [comment]
Uh, In my opinion the mapsmarker icons are super-ugly. They look that they are really drawn manually pixel-by pixel with no anti-aliasing :-/ So they won't be able to scale, and the result will look horrible on any HD screen.

They require that we display the license "CC-BY-SA 3.0 **Maps Icons Collection** https://mapicons.mapsmarker.com" somewhere on the map.

In contrast, the maki Icons are available as SVG and under a CC-0 license, which requires no attribution.

**Comment by josef-legacy-account** [comment]
Here a collection of possible specifications for the Icons for the SUSY-map:

**colours:**

dark blue: #212f4f
turquois: #95d5d2
yellow: #ffdd00
orange: #ffc20a

---

**Categories    ;   Icon    ;   Icon-Link**
- Food & Agriculture    ; milkbox & apple (carrot mit be better, but not available in this set) ;   https://mapicons.mapsmarker.com/markers/stores/food-drink/grocery/
- Fair Trade; World ;   https://mapicons.mapsmarker.com/markers/tourism/place-to-see/world/
- Reduce, reuse, repair, recycle; recycling-symbol; https://mapicons.mapsmarker.com/markers/industry/recycle/
- Housing & habitat ;   house   ;   https://mapicons.mapsmarker.com/markers/friends-family/house/
- Infrastructure & Ressorces    ;   wind-turbine    ;   https://mapicons.mapsmarker.com/markers/industry/electric-power/wind-turbine/
- Social inclusion  ;   shaking hands   ;   https://mapicons.mapsmarker.com/markers/health-education/health/social-services-provider/
- Education & Training  ;   chalkboard  ;   https://mapicons.mapsmarker.com/markers/health-education/education/school/
- Finance   ; money ;   https://mapicons.mapsmarker.com/markers/offices/bank/
- Active Citizenship    ; conversation bubble; https://mapicons.mapsmarker.com/markers/media/conversation/
- Self-Organization & mutuality ;   coins together  ;   https://mapicons.mapsmarker.com/markers/culture-entertainment/culture/museums/coin-museum/
- SUSY-map partner network  ;   house with flag     ;   https://mapicons.mapsmarker.com/markers/offices/embassy/

**Comment by josef-legacy-account** [comment]
![food_agriculture_plain_blue](https://cloud.githubusercontent.com/assets/4363790/18671425/4ee54a8a-7f44-11e6-9ec0-4397117e6b9d.png)
![food_agriculture_bubble_blue_invers](https://cloud.githubusercontent.com/assets/4363790/18671426/4ef1726a-7f44-11e6-8ec5-58b49baf7537.png)
![food_agriculture_turquoise_plain](https://cloud.githubusercontent.com/assets/4363790/18671629/1bdfa490-7f45-11e6-8a91-62dc5016a505.png)
![food_agriculture_turquoise_invers_bubble](https://cloud.githubusercontent.com/assets/4363790/18671626/1bd9ca70-7f45-11e6-93c4-f1bbe0b05b79.png)
![food_agriculture_yellow_plain](https://cloud.githubusercontent.com/assets/4363790/18671627/1bdba098-7f45-11e6-87b4-8063582228f3.png)
![food_agriculture_yellow_invers_bubble](https://cloud.githubusercontent.com/assets/4363790/18671628/1bdc0e66-7f45-11e6-8c65-976139b225d8.png)
![food_agriculture_orange_plain](https://cloud.githubusercontent.com/assets/4363790/18671634/2010217a-7f45-11e6-9e3a-586e9bf7fe95.png)
![food_agriculture_orange_invert_bubble](https://cloud.githubusercontent.com/assets/4363790/18671635/2010a690-7f45-11e6-872e-fc017ae6c6de.png)

**Comment by josef-legacy-account** [comment]
I like turquoise and yellow the most. 

Fair Trade:
![world_turquoise_invert_bubble](https://cloud.githubusercontent.com/assets/4363790/18671845/f339bdcc-7f45-11e6-8872-5d5add816ee0.png)
![world_turquoise_plain](https://cloud.githubusercontent.com/assets/4363790/18671847/f3409890-7f45-11e6-820a-ac14925c9e5a.png)
![world_yellow_invert_bubble](https://cloud.githubusercontent.com/assets/4363790/18671848/f343fa44-7f45-11e6-9d63-e06317d4d92a.png)
![world_yellow_plain](https://cloud.githubusercontent.com/assets/4363790/18671846/f33d1382-7f45-11e6-8043-0013ace6d7d2.png)

**Comment by species** [comment]
I've tried the Icons you committed in a fork, view it here:
https://susy-mapviewer.github.io/transformap-viewer/#6/48.122/15.436

A question arised: How to handle multiple categories per item? A lot of items have more than one type_of_initiative set, which results in more than one category. Currently it chooses the last one set, which is like random. This results in different icons displayed if you click a category to filter items only from one category.

**Comment by josef-legacy-account** [comment]
- Would it be possible to choose the first in the list of types_of_initiatives?  That most of the time ist he most appointed. 
  - I think it is ok, if different icons are visible within one category. Then the user can see immediately, that it is a multi-faceted project.
- From the colours, I would definitely say yellow bubble or turquoise bubble, with a slight tendency towards yellow. 

I will download and provide all items in yellow and turquoise with the colour starting in the naming, and the name of the category.

**Comment by josef-legacy-account** [comment]
@species I [uploaded the files](https://github.com/TransforMap/transformap-viewer/tree/gh-pages/assets) in yellow and turquoise. Would try yellow first.

The files are named:

colour_filter_category.png

**Comment by species** [comment]
The turquoise ones are much better, the yellow ones looked too similar to the cluster colors.

see  here: https://susy-mapviewer.github.io/transformap-viewer/#5/50.750/18.369

**Comment by josef-legacy-account** [comment]
top!
