### ISSUE TITLE
Clustering Library for POIs

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#4]
We need a clustering library (so that the points don't overlap much). 
@species  recommends [PruneCluster](https://github.com/SINTEF-9012/PruneCluster). 

> it offers high performance when applying filters.

_topic originated and moved from here: https://github.com/TransforMap/transformap.github.io/issues/24_

**Comment by species** [comment]
Implemented in 1a2ac3d43a6ac2e879da714a2fc03993ae3793c2.
