### ISSUE TITLE
small island problem

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#43]
Malta and Cypres mentioned, that they are basically not visible on the map. The problem will be solved, as they can put the zoom level on their map accordingly, and start in the appropriate places.

**Comment by josef-legacy-account** [comment]
solved here: https://github.com/susy-partners/transformap-viewer/issues/14

The zoom level and starting point for the maps to be implemented in their websites is close enough, so they are well visible.
