### ISSUE TITLE
Stamen Background Terrain does not have street level zoom

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#44]
Today at the SUSY-Webinar, we noticed, that Stamen Background Terrain does not have street level zoom. 

We could:
1. set another default view (Stamen Terrain or Humanitarian e.g.)
2. develop some kind of switch, that changes the map tiles at a certain zoom level

Given current priorities, I would prefer option 1.

**Comment by josef-legacy-account** [comment]
closed and moved here: https://github.com/TransforMap/transformap-viewer/issues/18
