### ISSUE TITLE
mobile version doesn't work

### ISSUE THREAD

**Issue by fthprojects** [TransforMap/transformap-viewer#45]
I tested the link on my mobile device (iphone SE) and it doesn't seem to work. I attach a screenshot with the page appeared after typing the url. Could you please check it?

![14872410_10211608377467627_1215675772_n](https://cloud.githubusercontent.com/assets/23098277/19765758/cd0cb7e2-9c52-11e6-8768-d07299566653.jpg)

**Comment by josef-legacy-account** [comment]
hello @fthprojects we are aware of the issue. I will merge your post there: https://github.com/TransforMap/transformap-viewer/issues/39

**Comment by josef-legacy-account** [comment]
This issue will be closed and further processd in #39

**Comment by josef-legacy-account** [comment]
@fthprojects thx for the feedback and image.

Just for you to know:
If you have an issue, comment, feedback, feature request, just post it as new one, and I will see, if there is already an existing one.

thx : )
