### ISSUE TITLE
map viewer not working on IE11

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#46]
The map viewer is not dispayed at the Internet Explorer 11. 

We noticed that today at the webinar. One participant used IE11 and could not open the map. Then we tested it with several others, who have IE, but use another standard browser. 

---

It might be important for some cohorts, as IE 11 still has a market share of 5% on Desktop. Depending on the complexity of the work, I would postpone the topic until we got the editor up and running?

@species how complex do you see enabiling IE11 to display the map (even with small glitches)?

**Comment by josef-legacy-account** [comment]
**I think we should enable a notification for IE 11, and currently postpone this issue:**

> Currently, the SUSY-map viewer does not provide for Internet Explorer 11, as it does not comply with current web standards. IE 11 is just relevant for 5% of all desktop-browsers, and not relevant for mobile browsers. With Windows 10, Microsoft decided to fade out IE11. 
> 
> For an good browsing experience with the SUSY-Map Viewer, please open the link to this page in firefox, chrome or safari, which comply to current web standards.
> 
> Thank you for your understanding. 
> We might develop the required adjustments for IE 11, but currently focus on other core parts of development in the SUSY-Map infrastructure.

**Comment by species** [comment]
The reason for this bug is that the old browsers do not support a technology called "Promises". It also seems to affect (at least some versions of) Safari on Apple devices, and Opera 12.
Working on a fallback solution.

**Comment by species** [comment]
A fallback solution was added.
Works on IE11, Android Browser and Opera12. Please test on iOS!

**Comment by species** [comment]
Confirmed to work also on iOS in #39.
