### ISSUE TITLE
Weblate - no access

### ISSUE THREAD

**Issue by fthprojects** [TransforMap/transformap-viewer#48]
I cannot register to the platform Weblate since I'm not receiving the confirmation e-mail and password from them. I sent them a message with the issue but I got no response.
Can we fix it somehow in order to procceed with the menu translation?
Thanks a lot

**Comment by josef-legacy-account** [comment]
@fthprojects hello Eirini,

thank you for your swift feedback, also for your feedback via email, which I will integrate in the next 2 days. 

---
Weblate is now working again, and I will send out the general information for everyone as soon as possible.
