### ISSUE TITLE
Navigation issues with non-fullscreen embedding in partner sites

### ISSUE THREAD

**Issue by lottallegra** [TransforMap/transformap-viewer#49]
**Menu Icon not intuitive:**
Menu not visible, when iframe width is not full screen width on large display (width = 735, for example):

![menu icon](https://cloud.githubusercontent.com/assets/23314904/20103405/2947f154-a5ca-11e6-80fa-d919aac763ff.png)

**Menu covers whole Map:**
The menu entries take up the whole width oft he iframe when opened and compleately cover up the underlying map PLUS there is no „BACK TO MAP“ button visible. Users might be lost in navigation. Idea: maximum menu entry width is around 80% so that part oft he underlying map remains visible and users can go back to map view by clicking on the still visible part oft he map.
![menu](https://cloud.githubusercontent.com/assets/23314904/20103437/4cce2e36-a5ca-11e6-98f1-ed42a3da1891.png)

**Comment by josef-legacy-account** [comment]
Hello @lottallegra thank you for your feedback and request. That is a vital part of the development process. 

I am going to divide different issues apart, so they can be taken on independently. Thank you for the screenshots and good reporting!!! 
In the next days and we will go through all of them and decide what we can resolve immediately!

**Comment by josef-legacy-account** [comment]
- Partner Site navigation Issues go here: https://github.com/susy-partners/transformap-viewer/issues/6
- Filter-Menu (funnel) Icon not clear in mobile mode goes here: https://github.com/TransforMap/transformap-viewer/issues/53
- Menu unexpectedly closing in mobile mode goes here: https://github.com/TransforMap/transformap-viewer/issues/54

**Comment by josef-legacy-account** [comment]
@lottallegra the main issue here is, that the mobile mode which has the properties you describe is set to early, so that it is already enabled from a with of ~800 px. We will try different settings for that in the next days. 

Once that setting is changed, the menu and everything else will look normal.

**Comment by josef-legacy-account** [comment]
@species can you prioritize this issue? Once resolved, we can move forward to rollout the process for partnersite integration. I assume, that subsequent feedback to the partnersite integration will mostly be enhancements or minor usability bugs.

Apart from resolving this issue, I would suggest, we decide what to resolve first, short before the next sprint planning.

**Comment by josef-legacy-account** [comment]
@species let´s set the breakpoint for mobile mode with 640 epx.

I found the measurement [here](https://msdn.microsoft.com/en-us/windows/uwp/layout/screen-sizes-and-breakpoints-for-responsive-design). It should fit for most smartphones in the market. Phones with HD screen will still be able to use the general menu, as the resolution is so very high

**Comment by species** [comment]
set to 640px for all 3 repositories.

**Comment by josef-legacy-account** [comment]
@lottallegra can you test in the inkota-Site, now it should work. Thank you!

**Comment by lottallegra** [comment]
![map](https://cloud.githubusercontent.com/assets/23314904/20310186/463e0146-ab4b-11e6-864d-b8667b3a51d6.PNG)

Its better, as the menu is not covering the whole map anymore. In some cases, however (as shown on the picture above), the menu is still covering about half of the map. The menu doesn't close entirely either, the only option is to click on different menu items so that a smaller menu popps up, which covers less of the map. Is it possible to make the menu close when one clicks on the map?

**Comment by josef-legacy-account** [comment]
The issue with the menu covering too much space is now moved here: https://github.com/susy-partners/transformap-viewer/issues/18, as the original issue is completed.
