### ISSUE TITLE
filter menu - food & ... / grow it yourself / community supported agriculture filter does not work

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#5]
The above mentioned filter does not seem to work. The same type_of_initiative with the same tag is also filtered in "food & ... / buy local / community supported agriculture" there it works and delivers 3 results in germany.

**Comment by josef-legacy-account** [comment]
same problem applies with "food bying circle" in the same categories. 
Maybe we should take "food bying circles" out of "grow it yourself and together". But let´s collect first.

**Comment by species** [comment]
Okay, this fix (665c7909353a1bff27d4a73bb243f338f53a128e) was longer.... but now supports multiple position of the same items in the menu tree.
Also the following items are here multiple times: Mutual Insurance, Seed Saving Initiatives.
