### ISSUE TITLE
Design Issue: Popup scroll bars

### ISSUE THREAD

**Issue by lottallegra** [TransforMap/transformap-viewer#51]
**Horizontal Scroll Bar in Info Box**
it would be nicer not having to scroll horizontally

![misc issues](https://cloud.githubusercontent.com/assets/23314904/20104060/c532ce52-a5cc-11e6-8794-d664eb2653ee.png)

**Comment by josef-legacy-account** [comment]
Me and another test-user noticed that as well, and share the opinion, 

that it would be much nicer without having the need to use the horizontal (on the bottom) scroll-bar in order to fully and beautifully get the content.
