### ISSUE TITLE
Order of menu items 

### ISSUE THREAD

**Issue by lottallegra** [TransforMap/transformap-viewer#52]
There doesn't seem to be a system in how the menu items are ordered (at least not in German and English). Is it possible to have menu items ordered alphabetically in each language? And possibly also to put the  "others" at the end of each menu list?

![menu order](https://cloud.githubusercontent.com/assets/23314904/20104253/947a8948-a5cd-11e6-930f-59c34b5deb16.PNG)

**Comment by josef-legacy-account** [comment]
There is 2 issues in the menu-structure which are split up as follows:

1. The Menu should probably best be in alphabetic order: https://github.com/susy-mapviewer/transformap-viewer/issues/14
2. Other should be the last category: https://github.com/TransforMap/transformap-viewer/issues/59

**Comment by species** [comment]
done with f35127195dca5064527abdef45c1040e485eb8b2.
Note that due to Unicode sorting, when mixing charsets (see e.g. greek) some charsets are sorted before others.
Others are hardcoded to be sorted on bottom.

**Comment by josef-legacy-account** [comment]
Very well done!
I suppose the hardcoding is well documented for future application?

Great, that you could fix the alphabetical order as well as the "other" category to be last. Very well done, looks neat and clean.
