### ISSUE TITLE
Advanced filter mode - language change / selected filters do not translate

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#55]
Reported from @lottallegra 
•	When I change languages, „Active Filters“ selected before do not change into the new language. When I select additional filters after changing laguages, they appear in the new laguage. So I get a mixed language filter list.

**Comment by josef-legacy-account** [comment]
• After changing languages slected filters are not highlighted (they do not turn from yellow to orange)
• No checkboxes displayed when I have activated the multiple filter option and then change languages

**Reproduction:**
1. Open the advanced filter mode
2. Change language
Result: The checkboxes are gone.

**Comment by species** [comment]
fixed in f984bdfa03d473fdf845af32820ab6539b119446. Filters do now reset when switching languages
