### ISSUE TITLE
Advanced filter mode - language change / 3rd level not highlighted

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#57]
- After changing languages,  slected filters are not highlighted (they do not turn from yellow to orange)

**Reproduction:**
1. Open the advanced filter mode
2. Change language
Result: On the 3rd level filtermenu structure, the selected items do not highlight in dark orange.

**Comment by species** [comment]
fixed with f984bdf. Filters reset now when switching languages.
