### ISSUE TITLE
menu disappears between 640 and ~760px width

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#58]
Fritz the technican of Inkota reported after the mobile breakpoint change to 640 px:

Clicking at a filter-subcategory, and afterwards on the main category, the entire menu structure diappears and turns dark blue.

I reproduced the bug, and it just shows between a width of 640 and ~760 px. Below 640 the map goes in mobile mode. There it switches to map-mode, if the same behavior is reproduced, which is reported as irritating here: https://github.com/TransforMap/transformap-viewer/issues/54. Above ~760px nothing happens.

![bild 5](https://cloud.githubusercontent.com/assets/4363790/20166922/3ee05502-a718-11e6-9cf3-f498b8610e01.jpg)

@species can you have a look into that?

**Comment by species** [comment]
Thanks for the hint, I forgot to change the value in the Javascript too. Should be fixed, please check.

**Comment by josef-legacy-account** [comment]
checked,
confirm: fixed.
