### ISSUE TITLE
Set "other" as last item in the menu structure

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#59]
As conversation with @species showed, the setting of putting "other" last in the order of the menu-structure might need settings in the taxonomy in http://base.transformap.co/. 

We set the priority of that item to a later point to keep focus on core infrastructure and easy issues now.

**Comment by species** [comment]
done with f35127195dca5064527abdef45c1040e485eb8b2.
I've hardcoded Q20 for the 'others' category, as well as the fact that "others" begin with others_ in the type_of_initiative tag.
