### ISSUE TITLE
Header in popups is linked. Link leads to general map overview

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#6]
The headers in the popup on the very top are linked. The link mis-leads to the general overview (entrance screen of the map) opening in a new window. 

There could be 2 possible ways to resolve it IMHO:

**1. Take the header-link out of the popup**
2. Link the header to the website, if a website is available.

Given time, ressources and more critical issiues, I would opt for 1.

**Comment by species** [comment]
fixed in 126c2d9d9a293ffd77660a0cb8fb1b58c20bf816.
