### ISSUE TITLE
Initiatives in DC (Developing Countries)

### ISSUE THREAD

**Issue by susyaustria** [TransforMap/transformap-viewer#64]
in the proposal it says that initatives in europe and the DC the susy projects cooperate with will be presented. at the moment the map focuses just on europe.

- is it foreseen that the dc are in there as well in a next step (like brazil, malaysia and 7 more)
- is it even possible to go out of europe with the map?
- in general (and this is something the project consortium has to discuss): does it make sense to bring in the DC - meaning do we have more than the "good practices" (which are 2) out of the research that can be shown on the map?

**Comment by josef-legacy-account** [comment]
@susyaustria there is several viewpoints on the issue, and first of all I need to declare, that in the initial agreement the SC decided, that neither the partners in the south, nor the people responsible for the mapping deployment have the capacities to handle the integration of the initiatives from the global south within that project.

That said, several specifications:

1. From a technical standpoint it is well possible to map anywhere in the world.
2. From the standpoint of capabilities to process further information we are beyond the point of feeling good about it. The editor is now a main focus, and even with the extension of the ressources we are quite low with energy, but still committed to make the whole setup of the SUSY-map a useful too.
3.1. If the partners from the global south fit into the same categories, as already developed, or developed in the 2nd iteration, they can simply be added independently with the editor. 
3.2. If they require other categories, they either need to be integrated in the 2nd iteration of the categories (please keep it simple, see point 2 above), or need to be integrated lateron, beyond the current assignment, as we agreed for the initial assignment.

Hope that clarifies, and hope for your understanding. Ultimately, it is an important goal to get the global south on the map. We just need to make sure to be able to handle one step at a time.

**Comment by susyaustria** [comment]
dear josef,
thanks for clarification and your first sentence explains everything:
in the initial agreement the SC decided, that neither the partners in the south, nor the people responsible for the mapping deployment have the capacities to handle the integration of the initiatives from the global south within that project.
that is why it is not there and with that it is good like it is. i missed or forgot the decision but i totally agree that it will be too much effort to focus on that as well. first of all we will be very happy to get a great partners-map :)
if it has been decided like this - great. just wanted to make sure we don't forget something.
