### ISSUE TITLE
SuSY partners in the map

### ISSUE THREAD

**Issue by susyaustria** [TransforMap/transformap-viewer#65]
as there is the need of mapping the susy partners it would be great to do so via the online-map (and not having an extra map about it on the website).
so can there be a category "SuSY Projectpartners" and then the organisations that are part of the project are mapped?
thanks!!

**Comment by josef-legacy-account** [comment]
@susyaustria that is already implemented : )

you can find the category "SUSY map partner network" in the menu, with all the partners integrated. It currently contains just basic information, that can be changed independently once the editor is in place.

https://susy-mapviewer.github.io/transformap-viewer

**Comment by susyaustria** [comment]
:-D strange i did not recognize it. great it is already there. thank you - now i saw it as well!!

**Comment by josef-legacy-account** [comment]
That is the best issues : ) when we can report, it is already implemented : )

If you have further issues, or ideas, please feel free. 
We just need to be aware, what we can handle at a time and within the project frame.
