### ISSUE TITLE
editable map does not display POIs

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#76]
@almereyda 

I just wanted to resolve issue #75, and noticed, that the [editable map ](https://susy-partners.github.io/tranis sformap-viewer/editable.html)  does not display the POIs, and therefor editing of existing points is not possible. 

The clusters are represented, just the POIs not.

**Comment by almereyda** [comment]
Dieses verflixte `editable`.

Klar, dass Lena gleich damit eine Mail an alle schickt:

- https://susy-partners.github.io/transformap-viewer/editable.html?background=mapnik#2/28.3/9.0
- https://github.com/susy-partners/transformap-viewer/blob/gh-pages/editable.html

**Comment by almereyda** [comment]
This is resolved with https://github.com/susy-partners/transformap-viewer/commit/a84da301a06f4fe20953964130d5b28c4a97c13c
