### ISSUE TITLE
mobile version - popup closing button hides behind zoom menu

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#8]
On my android phone (might also happen in other phones), the "x" closing button for the popup hides behind the zoom "+ - " menu. 

As the popup is currently set to stay within the borders of the screen, it always sticks there, and the button cannot be reached. That would technically not matter, as a click outside the popup also closes it, but it seems awkward, if one does not realize that, and tries to hit that "x".

**Comment by josef-legacy-account** [comment]
@species the button is really awsome. Just colour and size are a bit awkward.
- The size does not translate to the size of the smartphone screen, and is proportionally to big. If it could scale as the zoom-button does, that would be great.
- The colour somehow changes. While the menu is still visible, it is dark blue, and I can recognize the filter symbol (awsome by the way), once the menu is gone, and it is just the map and the button, the button turns so dark, that the sign is not visible any more, and it is just a dark button.

**Comment by species** [comment]
I reduced the size and style to match the [±] buttons.
The color shouldn't change. Which Browser are you using for testing? Could you attach a screenshot?

**Comment by josef-legacy-account** [comment]
new button looks awsome in size, colour and stlye! : ) yeah
