### ISSUE TITLE
mobile version - menu disappears once the map is in full view without option to go back

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#9]
On the mobile version with the menu above, there is no option to get the menu back, once the map is in full mode. Scrolling just scrolls the map. 

A button (arrow) or sthg. to go back to the menu would be helpful.

**Comment by species** [comment]
added a filter symbol in d65d105f5e4f4eeb339d62f538c63302a5c7c9a5.
